In [2]:
import tensorflow as tf

a = tf.constant([1,2,3]) 
b = tf.constant([4,5,6,7]) 

tile_a = tf.tile(tf.expand_dims(a, 1), [1, tf.shape(b)[0]])
# print(sess.run(tile_a))
tile_a = tf.expand_dims(tile_a, 2)
# print(sess.run(tile_a))
tile_b = tf.tile(tf.expand_dims(b, 0), [tf.shape(a)[0], 1])
# print(sess.run(tile_b))
tile_b = tf.expand_dims(tile_b, 2)
# print(sess.run(tile_b))

cartesian_product = tf.concat([tile_a, tile_b], axis=2) 

cart = tf.Session().run(cartesian_product)
cart1 = tf.Session().run(tf.reduce_prod(cartesian_product, axis=-1))

print(cart.shape) 
print(cart)
print(cart1)

(3, 4, 2)
[[[1 4]
  [1 5]
  [1 6]
  [1 7]]

 [[2 4]
  [2 5]
  [2 6]
  [2 7]]

 [[3 4]
  [3 5]
  [3 6]
  [3 7]]]
[[ 4  5  6  7]
 [ 8 10 12 14]
 [12 15 18 21]]
