This notebook is used for sample code (libraries, algorithms, ...) 

- **Define sparse matrix with scipy**

In [2]:
from scipy.sparse import lil_matrix
# define matrix X, size 1x5
# only element (0,1) = 1, all remained are 0
X = lil_matrix((1,5)).astype('float32')
X[0,1] = 1

# convert to full numpy array
X.toarray()

array([[0., 1., 0., 0., 0.]], dtype=float32)

In [12]:
Y = lil_matrix((1,5)).astype('int32')
Y[0,3] = 1
(X+Y).toarray()
X.T.dot(Y)

<5x5 sparse matrix of type '<class 'numpy.float64'>'
	with 1 stored elements in Compressed Sparse Row format>

In [14]:
X.T.dot(Y).toarray()

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
X.T.dot(Y)[1,3]

1.0

- **Create a range with numpy arange**

In [20]:
import numpy as np
# arange([start,] stop[, step,], dtype=None)
# Return evenly spaced values within a given interval.
np.arange(0, 5, 1, dtype='uint')

array([0, 1, 2, 3, 4], dtype=uint64)

In [22]:
np.arange(start=-1, stop=1, step=0.5, dtype='float32')

array([-1. , -0.5,  0. ,  0.5], dtype=float32)

- **Create Descatian product of index**

In [27]:
import itertools
iterables = [range(1), range(2), range(3)]
print(list(itertools.product(*iterables))) # 1x2x3 = 6 tuples

[(0, 0, 0), (0, 0, 1), (0, 0, 2), (0, 1, 0), (0, 1, 1), (0, 1, 2)]


- **Write and read JSON file**

In [46]:
import pandas as pd
# create data frame variable and its sinus
x1 = np.arange(-2,2,0.2)
x2 = np.sin(x1)
df = pd.DataFrame(data=np.append(x1.reshape(-1, 1), x1.reshape(-1, 1), axis=1), columns=['Var', 'Sinus'])

# export to json
df.to_json(path_or_buf='sin.json', orient='index')

# Usually read file
with open(file='sin.json', mode='r') as jfile:
    for line in jfile.readlines():
        print(line)

{"0":{"Var":-2.0,"Sinus":-2.0},"1":{"Var":-1.8,"Sinus":-1.8},"2":{"Var":-1.6,"Sinus":-1.6},"3":{"Var":-1.4,"Sinus":-1.4},"4":{"Var":-1.2,"Sinus":-1.2},"5":{"Var":-1.0,"Sinus":-1.0},"6":{"Var":-0.8,"Sinus":-0.8},"7":{"Var":-0.6,"Sinus":-0.6},"8":{"Var":-0.4,"Sinus":-0.4},"9":{"Var":-0.2,"Sinus":-0.2},"10":{"Var":-4.440892099e-16,"Sinus":-4.440892099e-16},"11":{"Var":0.2,"Sinus":0.2},"12":{"Var":0.4,"Sinus":0.4},"13":{"Var":0.6,"Sinus":0.6},"14":{"Var":0.8,"Sinus":0.8},"15":{"Var":1.0,"Sinus":1.0},"16":{"Var":1.2,"Sinus":1.2},"17":{"Var":1.4,"Sinus":1.4},"18":{"Var":1.6,"Sinus":1.6},"19":{"Var":1.8,"Sinus":1.8}}


In [55]:
# JSON read
import json
with open(file='sin.json', mode='r') as f:
    data = json.load(f)

print('JSON content:\n', data)
print('='*50, '\n', 'Item by item print:')
for key in data.keys():
    print('key:', key, '; value:', data[key])

JSON content:
 {'0': {'Var': -2.0, 'Sinus': -2.0}, '1': {'Var': -1.8, 'Sinus': -1.8}, '2': {'Var': -1.6, 'Sinus': -1.6}, '3': {'Var': -1.4, 'Sinus': -1.4}, '4': {'Var': -1.2, 'Sinus': -1.2}, '5': {'Var': -1.0, 'Sinus': -1.0}, '6': {'Var': -0.8, 'Sinus': -0.8}, '7': {'Var': -0.6, 'Sinus': -0.6}, '8': {'Var': -0.4, 'Sinus': -0.4}, '9': {'Var': -0.2, 'Sinus': -0.2}, '10': {'Var': -4.440892099e-16, 'Sinus': -4.440892099e-16}, '11': {'Var': 0.2, 'Sinus': 0.2}, '12': {'Var': 0.4, 'Sinus': 0.4}, '13': {'Var': 0.6, 'Sinus': 0.6}, '14': {'Var': 0.8, 'Sinus': 0.8}, '15': {'Var': 1.0, 'Sinus': 1.0}, '16': {'Var': 1.2, 'Sinus': 1.2}, '17': {'Var': 1.4, 'Sinus': 1.4}, '18': {'Var': 1.6, 'Sinus': 1.6}, '19': {'Var': 1.8, 'Sinus': 1.8}}
 Item by item print:
key: 0 ; value: {'Var': -2.0, 'Sinus': -2.0}
key: 1 ; value: {'Var': -1.8, 'Sinus': -1.8}
key: 2 ; value: {'Var': -1.6, 'Sinus': -1.6}
key: 3 ; value: {'Var': -1.4, 'Sinus': -1.4}
key: 4 ; value: {'Var': -1.2, 'Sinus': -1.2}
key: 5 ; value: {'Var'

In [56]:
with open(file='sin.json', mode='w') as f:
    json.dump(obj=data, fp=f)

In [57]:
!cat sin.json

{"0": {"Var": -2.0, "Sinus": -2.0}, "1": {"Var": -1.8, "Sinus": -1.8}, "2": {"Var": -1.6, "Sinus": -1.6}, "3": {"Var": -1.4, "Sinus": -1.4}, "4": {"Var": -1.2, "Sinus": -1.2}, "5": {"Var": -1.0, "Sinus": -1.0}, "6": {"Var": -0.8, "Sinus": -0.8}, "7": {"Var": -0.6, "Sinus": -0.6}, "8": {"Var": -0.4, "Sinus": -0.4}, "9": {"Var": -0.2, "Sinus": -0.2}, "10": {"Var": -4.440892099e-16, "Sinus": -4.440892099e-16}, "11": {"Var": 0.2, "Sinus": 0.2}, "12": {"Var": 0.4, "Sinus": 0.4}, "13": {"Var": 0.6, "Sinus": 0.6}, "14": {"Var": 0.8, "Sinus": 0.8}, "15": {"Var": 1.0, "Sinus": 1.0}, "16": {"Var": 1.2, "Sinus": 1.2}, "17": {"Var": 1.4, "Sinus": 1.4}, "18": {"Var": 1.6, "Sinus": 1.6}, "19": {"Var": 1.8, "Sinus": 1.8}}